config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  scope :admin do
    get '/', to: 'admin#index'
    post '/', to: 'admin#create_experiment', as: :create_experiment
    patch '/', to: 'admin#complete_experiment', as: :complete_experiment
    post '/add_devices', to: 'admin#add_test_devices', as: :add_test_devices
    get '/logout', to: 'admin#logout'
    match '/authenticate', to: 'admin#authenticate', via: %i[get post]
    match '/create_user', to: 'admin#create_user', via: %i[get post]
  end
  get '/change_locale', to: 'application#change_locale', as: :change_locale
  get 'up' => 'rails/health#show', as: :rails_health_check
  root 'admin#index'
  mount Api::Engine, at: '/api'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  self.implicit_order_column = 'created_at'

  def as_dto
    raise NotImplementedError
  end
end

app/models/device.rb
# frozen_string_literal: true

class Device < ApplicationRecord
  belongs_to :user, optional: true
  has_many :device_experiments, dependent: :destroy, inverse_of: :device
  has_many :experiments, through: :device_experiments

  scope :with_user, -> { where.not(user_id: nil) }
  scope :without_user, -> { where(user_id: nil) }
  scope :with_experiments, -> { joins(:device_experiments).distinct }
  scope :without_experiments, -> { where.missing(:device_experiments) }

  def as_dto
    {
      device_token: id,
      user: user&.as_dto,
      experiments: experiments.map(&:as_dto) # ideally this should be compressed with gzip and encoded in base 64
    }
  end

  after_create :assign_experiment

  private

  def assign_experiment
    Experiment.lock.transaction do
      grouped_experiments = Experiment.not_completed.order(chance: :asc).group_by(&:key)

      find_and_assign_experiment(grouped_experiments)
    end
  end

  def find_and_assign_experiment(grouped_experiments)
    grouped_experiments.each do |experiment_key, experiments_array|
      next if experiments.exists?(key: experiment_key)

      handle_experiments(experiments_array)
    end
  end

  def handle_experiments(experiments_array)
    experiments_array.each_with_index do |experiment, index|
      distribution = Distribution.find_by(key: experiment.key, value: experiment.value)
      if distribution.nil?
        device_experiments.create!(experiment:)
        break
      end

      next if distribution.percent_of_key.to_f >= experiment.chance && index != experiments_array.size - 1

      assign_random_experiment(experiments_array, experiment)
      break
    end
  end

  def assign_random_experiment(experiments_array, experiment)
    unfulfilled_experiment = Distribution.where(key: experiment.key).not_fulfilled.first&.experiment
    experiment = unfulfilled_experiment || experiments_array.sample
    device_experiments.create!(experiment:)
  end
end

app/models/device_experiment.rb
# frozen_string_literal: true

class DeviceExperiment < ApplicationRecord
  belongs_to :device
  belongs_to :experiment
end

app/models/distribution.rb
# frozen_string_literal: true

class Distribution < ApplicationRecord
  attribute :percent_of_total, :float
  attribute :percent_of_key, :float

  # rubocop:disable Rails/InverseOf
  belongs_to :experiment, optional: true, foreign_key: :id
  # rubocop:enable Rails/InverseOf
  scope :not_fulfilled, -> { where('percent_of_key < chance') }

  default_scope { where.not(key: nil).or(where.not(value: nil)) }

  def readonly?
    true
  end
end

app/models/experiment.rb
# frozen_string_literal: true

class Experiment < ApplicationRecord
  has_many :device_experiments, dependent: :destroy, inverse_of: :experiment
  has_many :devices, through: :device_experiments
  has_many :distributions, dependent: :nullify

  scope :with_devices, -> { joins(:device_experiments).distinct }
  scope :without_devices, -> { where.missing(:device_experiments) }
  scope :not_completed, -> { where(completed: false) }
  scope :completed, -> { where(completed: true) }

  def as_dto
    {
      key:,
      value:
    }
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password
  has_many :devices, dependent: :nullify

  scope :with_devices, -> { joins(:devices).distinct }
  scope :without_devices, -> { where.missing(:devices) }

  enum role: { user: 0, admin: 1 }

  normalizes :email, with: ->(email) { email.strip.downcase }
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, presence: true, length: { minimum: 8 }, if: -> { new_record? || !password.nil? }
  validates :role, presence: true, inclusion: { in: roles.keys }

  def as_dto
    {
      id:,
      email:,
      role:
    }
  end
end

app/controllers/admin_controller.rb
# frozen_string_literal: true

class AdminController < ApplicationController
  before_action :authenticate_user!, except: %i[authenticate create_user]

  def index; end

  def authenticate
    return unless request.post?

    user = User.find_by(email: params[:email])

    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      show_notice('Invalid email or password')
    end
  end

  def create_user; end

  def create_experiment
    key = params[:key]

    params[:value].each_with_index do |value, index|
      chance = params[:chance][index]
      Experiment.create!(key:, value:, chance:)
    end

    redirect_to root_url
  rescue StandardError => e
    show_notice(e.message)
  end

  def complete_experiment
    Experiment.where(key: params[:key]).update(completed: true)
    redirect_to root_url
  rescue StandardError => e
    show_notice(e.message)
  end

  def add_test_devices
    AddTestDevicesJob.perform_later(session.id.to_s, params[:count].to_i)
    redirect_to root_url
  rescue StandardError => e
    show_notice(e.message)
  end

  def logout
    reset_session
    redirect_to root_path
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  helper_method :current_user
  add_flash_types :success, :warning, :danger, :info

  rescue_from StandardError do |exception|
    @error = [exception.class, exception.message]
    @error << exception.backtrace[..5] if Rails.env.development?
    respond_to do |format|
      format.html { render template: 'error/error', status: :internal_server_error }
      format.json do
        render json: { error: { error_type: @error.first, error_message: @error[1], error_backtrace: @error.last } },
               status: :internal_server_error
      end
    end
  end

  def change_locale
    session[:locale] = params[:locale] || I18n.default_locale
    I18n.locale = session[:locale]
    redirect_to root_path
  end

  private

  def show_notice(message)
    NotificationJob.perform_later(session.id.to_s, message)
  end

  before_action do
    year_created = '2023'
    year = Date.current.year.to_s

    @year = year == year_created ? year : "#{year_created} - #{year}"
  end

  def authenticate_user!
    return if current_user

    redirect_to authenticate_path
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/admin_helper.rb
# frozen_string_literal: true

module AdminHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/experiments_helper.rb
# frozen_string_literal: true

module ExperimentsHelper
end

app/views/admin/_admin.html.erb
<table class="tui-table-grid main-table">
  <tbody>
  <tr>
    <td rowspan="2" height="90%">
      <div class="tui-window main-stats">
        <%= render 'stats/general' %>
      </div>
    </td>
    <td width="30%" height="3%" class="center">
      <div class="tui-window main-experiment-create">
        <%= render 'stats/experiments' %>
      </div>
    </td>
  </tr>
  <tr>
    <td width="25" height="60%">
      <div class="tui-window main-experiment-create">
        <%= render 'stats/devices' %>
      </div>
    </td>
  </tr>
  <tr>
    <td height="3%" colspan="2">
    </td>
  </tr>
  </tbody>
</table>

app/views/admin/authenticate.html.erb
<div class="tui-window">
  <fieldset class="tui-fieldset">
    <legend class="center"><%= I18n.t('labels.sign_in') %></legend>
    <%= form_with url: authenticate_path, method: :post do |form| %>
      <div>
        <%= form.label :email, I18n.t('labels.email') %>
        <%= form.email_field :email, required: true, class: 'tui-input' %>
      </div>

      <div>
        <%= form.label :password, I18n.t('labels.password') %>
        <%= form.password_field :password, required: true, class: 'tui-input' %>
      </div>

      <div>
        <%= form.submit I18n.t('labels.submit'), class: 'tui-button' %>
      </div>
    <% end %>
  </fieldset>
</div>

app/views/admin/create_user.html.erb
<h1>Admin#create_user</h1>
<p>Find me in app/views/admin/create_user.html.erb</p>

app/views/admin/index.html.erb
<% if current_user.admin? %>
  <%= render 'admin/admin' %>
<% else %>
  <p><%= I18n.t('messages.not_admin') %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ExperimentalApi</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag 'actioncable.js' %>
</head>

<body>
<nav class="tui-nav main-nav">
  <ul>
    <li class="tui-dropdown">
      <span class="red-168-text"><%= I18n.t('labels.links')[0] %></span><%= I18n.t('labels.links')[1..] %>
      <div class="tui-dropdown-content">
        <ul>
          <li>
            <a href="<%= root_path %>"><span class="red-168-text"><%= I18n.t('labels.home')[0] %></span><%= I18n.t('labels.home')[1..] %>
            </a>
          </li>
        </ul>
      </div>
    </li>
    <% if session[:user_id].present? %>
      <li class="tui-dropdown">
        <span class="red-168-text"><%= current_user.email[0] %></span><%= current_user.email[1..] %>
        <div class="tui-dropdown-content">
          <ul>
            <li>
              <%= link_to raw('<span class="red-168-text">' + I18n.t('labels.log_out')[0] + '</span>' + I18n.t('labels.log_out')[1..]), logout_path %>
            </li>
          </ul>
        </div>
      </li>
    <% else %>
      <li class="tui-dropdown">
        <span class="red-168-text"><%= I18n.t('labels.identity')[0] %></span><%= I18n.t('labels.identity')[1..] %>
        <div class="tui-dropdown-content">
          <ul>
            <li>
              <a href="<%= authenticate_path %>"><span class="red-168-text"><%= I18n.t('labels.sign_in')[0] %></span><%= I18n.t('labels.sign_in')[1..] %>
              </a></li>
          </ul>
        </div>
      </li>
    <% end %>
    <li class="tui-dropdown">
      <span class="red-168-text"><%= I18n.t('labels.locale')[0] %></span><%= I18n.t('labels.locale')[1..] %>
      <div class="tui-dropdown-content">
        <ul>
          <li>
            <a href="<%= change_locale_path(locale: I18n.t('labels.next_locale')) %>"><span class="red-168-text"><%= I18n.t('labels.next_locale')[0] %></span><%= I18n.t('labels.next_locale')[1..] %>
            </a>
          </li>
        </ul>
      </div>
    </li>
    <span class="tui-datetime" data-format="h:m:s a"></span>
  </ul>
</nav>

<div class="tui-bg-blue-white main-body center">
  <div id="notice">
  </div>
  <%= yield %>
</div>

<div class="tui-statusbar">
  <ul>
    <li><span class="red-168-text"><%= I18n.t('labels.svck_dev')[0] %></span><%= I18n.t('labels.svck_dev')[1..] %></li>
    <span class="tui-statusbar-divider"></span>
    <li>
      <span class="red-168-text"><%= I18n.t('labels.experiments_api')[0] %></span><%= I18n.t('labels.experiments_api')[1..] %>
    </li>
    <span class="tui-statusbar-divider"></span>
    <li><span class="red-168-text"><%= @year[0] %></span><%= @year[1..] %></li>
  </ul>
</div>
</body>

<script type=application/javascript>
    const cable = ActionCable.createConsumer();
    cable.subscriptions.create({
            channel: 'NotificationChannel',
            session_id: "<%= session.id %>"
        },
        {
            received: function (data) {
                const errorsDiv = document.querySelector('#notice');
                const newError = document.createElement('p');
                newError.textContent = data;
                errorsDiv.appendChild(newError);
                setTimeout(function () {
                    errorsDiv.removeChild(newError);
                }, 10000);
            }
        });
</script>

<script type=application/javascript>
    /**
     * Replacement for jQuery's $(document).ready() function.
     * This is handy in making sure stuff fires after the DOM is ready to be touched.
     * Stolen from:https://stackoverflow.com/a/53601942/344028
     *
     * @param fn Callback.
     */
    function domReady(fn) {
        // If we're early to the party
        document.addEventListener('DOMContentLoaded', fn);

        // If late; I mean on time.
        if (document.readyState === 'interactive' || document.readyState === 'complete') {
            fn();
        }
    }

    /**
     * TuiTabs controller
     */
    function tabsController() {
        // Get all the tab elements (typically li tags).
        const tabs = document.getElementsByClassName('tui-tab');

        if (!tabs.length) {
            // No tabs found, return early and save a couple CPU cycles.
            return;
        }

        for (const tab of tabs) {
            // Add click listeners to them.
            tab.addEventListener('click', function (e) {

                // Check if the clicked tab is disabled
                if (e.target.classList.contains("disabled")) {
                    return;
                }

                // Remove the 'active' class from any and all tabs.
                for (const otherTab of tabs) {
                    otherTab.classList.remove('active');
                }

                // Get the content element.
                const tabContents = document.getElementsByClassName('tui-tab-content');

                if (tabContents) {
                    for (const tabContent of tabContents) {
                        // Hide all tab contents.
                        tabContent.style.display = 'none';
                    }
                } else {
                    throw 'No tab content elements found.'
                }

                // Get the id of the tab contents we want to show.
                const tabContentId = e.target.getAttribute('data-tab-content');

                if (tabContentId) {
                    const tabContent = document.getElementById(tabContentId);
                    if (tabContent) {
                        // Show the tab contents.
                        tabContent.style.display = 'block';
                    } else {
                        throw 'No tab content element with id "' + tabContentId + '" found.';
                    }
                }
                // We are not going to throw an error here, since we could make the tab do something else that a tab
                // normally wouldn't do.

                // Set the clicked tab to have the 'active' class so we can use it in the next part.
                e.target.classList.add('active');

            });
        }

        // Grab the first tab with the active class.
        const activeTab = document.querySelector('.tui-tab.active');
        if (activeTab) {
            // Now click it 'click' it.
            activeTab.click();
        } else {
            // Nothing found, just click the first tab foud.
            tabs[0].click()
        }
    }

    /**
     * Date/time field controller
     */
    function datetimeController() {
        // Get date/time elements.
        const clocks = document.getElementsByClassName('tui-datetime');

        if (!clocks.length) {
            // No date time elements found, return early and save a couple CPU cycles.
            return;
        }

        // Kick off our clock interval stuff.
        datetimeInterval();

        // Synchronize time and set interval to control the clocks
        setTimeout(() => {
            setInterval(datetimeInterval, 1000);
        }, 1000 - new Date().getMilliseconds());

        function datetimeInterval() {
            for (const clock of clocks) {
                if (clock === null) {
                    continue;
                }

                // Get the format we want to display in the element.
                let format = clock.getAttribute('data-format');

                // parse out the date and time into constants.
                const today = new Date();
                const month = (today.getMonth() + 1).toString().padStart(2, '0');
                const day = today.getDate().toString().padStart(2, '0');
                const dayOfWeek = (today.getDay() + 1).toString().padStart(2, '0');
                const year = today.getFullYear().toString();
                const hour = today.getHours().toString().padStart(2, '0');
                const hour12 = (parseInt(hour) + 24) % '12' || '12';
                const minute = today.getMinutes().toString().padStart(2, '0');
                const second = today.getSeconds().toString().padStart(2, '0');
                const ampm = parseInt(hour) >= 12 ? 'PM' : 'AM';

                // Replace based on the format.
                format = format.replace('M', month);
                format = format.replace('d', day);
                format = format.replace('e', dayOfWeek);
                format = format.replace('y', year);
                format = format.replace('H', hour);
                format = format.replace('h', hour12);
                format = format.replace('m', minute);
                format = format.replace('s', second);
                format = format.replace('a', ampm);

                // Show it in the element.
                clock.innerHTML = format;
            }
        }
    }

    /**
     * Sidenav Controller
     * There should only side navigation element at the moment.
     */
    function sidenavController() {
        // Get the side navigation button (there should be only one, but if not, we are getting the first one).
        const sideNavButton = document.querySelector('.tui-sidenav-button');

        if (!sideNavButton) {
            // No side navigation button found, return early and save a couple CPU cycles.
            return;
        }

        // Add the click event listener to the buttons.
        sideNavButton.addEventListener('click', () => {
            // Get the side navigation element (there should be only one, but if not, we are getting the first one).
            const sideNav = document.querySelector('.tui-sidenav');

            if (sideNav) {
                if (sideNav.classList.contains('active')) {
                    sideNav.classList.remove('active');
                } else {
                    sideNav.classList.add('active');
                }
            } else {
                throw 'No sidenav element found.'
            }
        });
    }

    /**
     * Modal controller
     */
    function modalController() {
        // Get the overlap (overlay) element (there should be only one, but if not, we are getting the first one).
        const tuiOverlap = document.querySelector('.tui-overlap');

        if (!tuiOverlap) {
            // No overlap found element, return early and save a couple CPU cycles.
            return;
        }

        // Find modal buttons.
        const modalButtons = document.getElementsByClassName('tui-modal-button');
        for (const modalButton of modalButtons) {
            // Add the click event listener to the buttons.
            modalButton.addEventListener('click', (e) => {
                // Show the overlap.
                tuiOverlap.classList.add('active');

                // Get the display element for the modal.
                const modalId = e.target.getAttribute('data-modal');

                if (modalId) {
                    const modal = document.getElementById(modalId);

                    if (modal) {
                        // Show it.
                        modal.classList.add('active');
                    } else {
                        throw 'No modal element with id of "' + modalId + '" found.';
                    }
                } else {
                    throw 'Modal close button data-modal attribute is empty or not set.'
                }
            });
        }

        // Find the close modal buttons.
        const modalCloseButtons = document.getElementsByClassName('tui-modal-close-button');

        if (modalButtons.length > 0 && !modalCloseButtons.length) {
            // A modal without a close button, is a bad modal.
            throw 'No modal close buttons found.'
        }

        for (const modalCloseButton of modalCloseButtons) {
            // Add the click event listener to the buttons.
            modalCloseButton.addEventListener('click', (e) => {
                // Hide the the overlap.
                tuiOverlap.classList.remove('active');

                // Get the display element id for the modal.
                const modalId = e.target.getAttribute('data-modal');

                if (modalId) {
                    // Get the modal element.
                    const modal = document.getElementById(modalId);

                    if (modal) {
                        // Hide it.
                        modal.classList.remove('active');
                    } else {
                        throw 'No modal element with id of "' + modalId + '" found.';
                    }
                } else {
                    throw 'Modal close button data-modal attribute is empty or not set.'
                }
            });
        }
    }

    /**
     * Init: This is at the bottom to make sure it is fired correctly.
     */
    domReady(function () {
        tabsController();
        datetimeController();
        sidenavController();
        modalController();
    });
</script>
</html>

app/views/stats/_devices.html.erb
<%= render 'stats/devices/add_test' %>
<%= render 'stats/devices/rand_with_experiment' %>
<%= render 'stats/devices/rand_without_experiment' %>

app/views/stats/_experiments.html.erb
<%= render 'stats/experiments/create' %>
<%= render 'stats/experiments/update' %>

app/views/stats/_general.html.erb
<fieldset class="tui-fieldset">
  <legend><%= I18n.t('labels.stats') %></legend>
  <%= render 'stats/general/table' %>
  <%= render 'stats/general/devices' %>
</fieldset>

app/views/stats/devices/_add_test.html.erb
<fieldset class="tui-fieldset">
  <legend><%= I18n.t('labels.add_test_devices') %></legend>
  <%= form_with(url: add_test_devices_path, method: "post", local: true) do |form| %>
    <div id="key-field">
      <%= form.label :amount %>

      <%= form.number_field :count, step: 1, class: 'tui-input', placeholder: I18n.t('labels.count_placeholder') %>
    </div>

    <%= form.submit I18n.t('labels.add'), class: 'tui-button' %>
  <% end %>

</fieldset>

app/views/stats/devices/_rand_with_experiment.html.erb
<fieldset class="tui-fieldset">
  <legend><%= I18n.t('labels.random_devices_with_experiments') %></legend>
  <% Device.with_experiments.sample(10).pluck(:id).each do |device| %>
    <p><%= device %></p>
  <% end %>
</fieldset>

app/views/stats/devices/_rand_without_experiment.html.erb
<fieldset class="tui-fieldset">
  <legend><%= I18n.t('labels.random_devices_without_experiments') %></legend>
  <% Device.without_experiments.sample(10).pluck(:id).each do |device| %>
    <p><%= device %></p>
  <% end %>
</fieldset>

app/views/stats/experiments/_create.html.erb
<fieldset class="tui-fieldset">
  <legend><%= I18n.t('labels.create_experiments') %></legend>
  <%= form_with(url: create_experiment_path, method: "post", local: true) do |form| %>
    <div id="key-field">
      <%= form.label :key %>
      <%= form.text_field :key, class: 'tui-input' %>
    </div>

    <div id="value-chance-fields">
      <div id="value-chance-0">
        <%= form.label :value_and_chance %>
        <%= form.text_field :value, multiple: true, class: 'tui-input', placeholder: I18n.t('labels.value_placeholder') %>
        <%= form.number_field :chance, step: 0.1, multiple: true, class: 'tui-input', placeholder: I18n.t('labels.chance_placeholder') %>
        %
      </div>
    </div>

    <button type="button" class="tui-button" id="add-value-chance">+</button>

    <%= form.submit I18n.t('labels.add'), class: 'tui-button' %>
  <% end %>

</fieldset>


<script>
    document.getElementById('add-value-chance').addEventListener('click', function () {
        const valueChanceFields = document.getElementById('value-chance-fields');
        const newValueChanceField = document.createElement('div');
        newValueChanceField.innerHTML = '<input type="text" name="value[]" multiple="true" class="tui-input" placeholder="<%= I18n.t('labels.value_placeholder') %>">' +
            '<input type="number" step="0.1" name="chance[]" multiple="true" class="tui-input" placeholder="<%= I18n.t('labels.chance_placeholder') %>">';
        valueChanceFields.appendChild(newValueChanceField);
    });
</script>

app/views/stats/experiments/_update.html.erb
<fieldset class="tui-fieldset">
  <legend><%= I18n.t('labels.update_experiments') %></legend>
  <% Experiment.not_completed.select(:key).uniq { |e| e.key }.each do |experiment| %>
    <%= form_with(url: complete_experiment_path, method: :patch, local: true) do |form| %>
      <%= form.hidden_field :key, value: experiment.key %>
      <%= form.submit I18n.t('labels.complete_key', key: experiment.key), class: 'tui-button' %>
    <% end %>
  <% end %>
</fieldset>

app/views/stats/general/_devices.html.erb
<fieldset class="tui-fieldset">
  <legend><%= I18n.t('labels.devices') %></legend>
  <%= Device.count %> <%= I18n.t('labels.total_devices') %>
  <hr class="tui-divider"></hr>
  <%= Device.with_experiments.count %> <%= I18n.t('labels.devices_with_experiments') %>
  <hr class="tui-divider"></hr>
  <%= Device.without_experiments.count %> <%= I18n.t('labels.devices_without_experiments') %>
  <hr class="tui-divider"></hr>
  <%= Device.with_user.count %> <%= I18n.t('labels.devices_with_registered_users') %>
  <hr class="tui-divider"></hr>
  <%= Experiment.completed.count %> <%= I18n.t('labels.completed_experiments') %>
</fieldset>

app/views/stats/general/_table.html.erb
<fieldset class="tui-fieldset">
  <legend><%= I18n.t('labels.general') %></legend>
  <table class="tui-table">
    <thead>
    <tr>
      <th><%= I18n.t('labels.key') %></th>
      <th><%= I18n.t('labels.value') %></th>
      <th><%= I18n.t('labels.amount') %></th>
      <th><%= I18n.t('labels.total_devices') %></th>
      <th><%= I18n.t('labels.percent_of_total_devices') %></th>
      <th><%= I18n.t('labels.devices_with_this_key') %></th>
      <th><%= I18n.t('labels.percent_of_devices_with_this_key') %></th>
      <th><%= I18n.t('labels.chance') %></th>
      <th><%= I18n.t('labels.completed') %></th>
    </tr>
    </thead>
    <tbody>
    <% Distribution.all.each do |distribution| %>
      <tr>
        <td><%= distribution.key %></td>
        <td><%= distribution.value %></td>
        <td><%= distribution.amount %></td>
        <td><%= distribution.total_devices %></td>
        <td><%= distribution.percent_of_total %>%</td>
        <td><%= distribution.key_devices %></td>
        <td><%= distribution.percent_of_key %>%</td>
        <td><%= distribution.chance %>%</td>
        <td>
          <%= Experiment.find(distribution.id).completed %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</fieldset>